# Generated by Django 3.1.7 on 2021-04-25 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0003_blooddonar_profession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blooddonar',
            name='profession',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
