# Generated by Django 3.1.7 on 2021-04-27 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0005_auto_20210425_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='blooddonar',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
