# Generated by Django 3.1.7 on 2021-04-27 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0007_auto_20210427_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='title',
        ),
    ]
