# Generated by Django 3.1.7 on 2021-04-28 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0008_remove_image_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AddField(
            model_name='blooddonar',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
