# Generated by Django 3.1.7 on 2021-04-28 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0009_auto_20210428_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blooddonar',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics'),
        ),
    ]
